---
source: external-crates/move/crates/move-transactional-test-runner/src/framework.rs
---
processed 6 tasks

init:
A: object(0,0)

task 1, lines 6-14:
//# publish --sender A --upgradeable
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5814000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 16-31:
//# upgrade --package test --upgrade-capability 1,1 --sender A
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6338400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 3, line 33:
//# run test::clever_error_post_v48::test_new_error --sender A
Error: Transaction Effects Status: Move Abort in test::clever_error_post_v48::test_new_error (function index 1) at offset 1 at line 26
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("clever_error_post_v48") }, function: 1, instruction: 1, function_name: Some("test_new_error") }, 13906834286012661763), source: Some(VMError { major_status: ABORTED, sub_status: Some(13906834286012661763), message: Some("fake(1,0)::clever_error_post_v48::test_new_error at offset 1"), exec_state: None, location: Module(ModuleId { address: fake(1,0), name: Identifier("clever_error_post_v48") }), indices: [], offsets: [(FunctionDefinitionIndex(1), 1)] }), command: Some(0) } }

task 4, line 35:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 37-65:
//# run-graphql
Response: {
  "data": {
    "originalPackage": {
      "address": "0x68349aa7d30708d4eebb096543f96673012cb82b3584a6671038bd30d32a83a6"
    },
    "upgradedPackage": {
      "address": "0xe31589945850a4ba7416dd0e300a3c7e2b36cd25f5e113895e8ea3cb772e209c"
    },
    "cleverErrorPostV48": {
      "executionError": {
        "abortCode": "13906834286012661763",
        "sourceLineNumber": 26,
        "instructionOffset": 1,
        "identifier": "ENewError",
        "constant": "New error in v2",
        "message": "Error in 1st command, from '0xe31589945850a4ba7416dd0e300a3c7e2b36cd25f5e113895e8ea3cb772e209c::clever_error_post_v48::test_new_error' (line 26), abort 'ENewError': New error in v2",
        "module": {
          "name": "clever_error_post_v48",
          "package": {
            "address": "0xe31589945850a4ba7416dd0e300a3c7e2b36cd25f5e113895e8ea3cb772e209c"
          }
        },
        "function": {
          "name": "test_new_error",
          "module": {
            "name": "clever_error_post_v48"
          }
        }
      }
    }
  }
}
