# Broken external resolver returns correct output but exits with an error code

[package]
name = "example"
edition = "2024.beta"
license = "Apache-2.0"
authors = ["Move Team"]

[environments]
mainnet = "35834a8a"

[dependencies.mock.r.mock-resolver]
exit_code = 1
stdout = """
# a valid response
[responses."(None, mock)"]
resolved = { local = "." }
warnings = []

[responses."(Some(\\\"mainnet\\\"), mock)"]
resolved = { local = "." }
warnings = []
"""
stderr = "stderr output"
